$(".fruits").owlCarousel({
    margin:30,
    responsive:{
        0:{
            items:2,
            merge:true,
            loop:true,
            nav:true,
            navText:["<b>‹</b>","<b>›</b>"]
        },
        400:{
            items:3,
            merge:true,
            loop:true,
            nav:true,
            navText:["<b>‹</b>","<b>›</b>"]
        },
        700:{
            items:3.5,
            merge:true,
            loop:true,
            nav:true,
            navText:["<b>‹</b>","<b>›</b>"]
        }
    }
});

$(".character").owlCarousel({
    margin:30,
    responsive:{
        0:{
            items:2,
            merge:true,
            loop:true,
            nav:true,
            navText:["<b>‹</b>","<b>›</b>"]
        },
        600:{
            items:3.5,
            merge:true,
            loop:true,
            nav:true,
            navText:["<b>‹</b>","<b>›</b>"]
        }
    }
})
